### ISSUE TITLE
Can i use this module with angular 5.0

### ISSUE THREAD

**Issue by chusri** [isopen/ngx-cable#1]
after i ad the module to my project i got this error

thank.

<img width="1078" alt="screenshot 2018-01-04 15 26 36" src="https://user-images.githubusercontent.com/2667287/34555346-cfc56eb8-f163-11e7-9a66-dae8cc2991d9.png">

**Comment by isopen** [comment]
Try it: 
npm i util --save
npm i rxjs --save
npm i actioncable --save
**npm start** instead of **ng serve**

If you persistently want to use **ng serve**, you need to configure **tsconfig** in your application.
https://github.com/angular/angular/issues/20091
Example https://github.com/isopen/soc/blob/master/frontend/src/tsconfig.app.json

Perhaps you do not have the necessary dependencies.
Example angular 5.1.1 https://github.com/isopen/soc/blob/master/frontend/package.json

Bast Regards

**Comment by chusri** [comment]
solved thanks.
